name: klyc
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  rename: ^2.1.1
  cloud_firestore: ^4.8.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  get_it: ^7.6.0
  provider: ^6.0.5
  fluttertoast: ^8.2.2
  google_sign_in: ^6.1.4
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2
  flutter_native_splash: ^2.3.2
  shimmer: ^3.0.0
  path_provider: ^2.0.5
  image_gallery_saver: ^2.0.3
  brain_fusion: ^0.1.1
  flutter_facebook_auth: ^6.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/